// Code generated by ent, DO NOT EDIT.

package share

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/kakra/ferry/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldID, id))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldOwnerID, v))
}

// PublicTokenEncrypted applies equality check predicate on the "public_token_encrypted" field. It's identical to PublicTokenEncryptedEQ.
func PublicTokenEncrypted(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldPublicTokenEncrypted, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldTokenHash, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldPasswordHash, v))
}

// UnlockVersion applies equality check predicate on the "unlock_version" field. It's identical to UnlockVersionEQ.
func UnlockVersion(v int) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldUnlockVersion, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldTitle, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldNote, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldCreatedAt, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...uuid.UUID) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDIsNil applies the IsNil predicate on the "owner_id" field.
func OwnerIDIsNil() predicate.Share {
	return predicate.Share(sql.FieldIsNull(FieldOwnerID))
}

// OwnerIDNotNil applies the NotNil predicate on the "owner_id" field.
func OwnerIDNotNil() predicate.Share {
	return predicate.Share(sql.FieldNotNull(FieldOwnerID))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldType, vs...))
}

// PublicTokenEncryptedEQ applies the EQ predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldPublicTokenEncrypted, v))
}

// PublicTokenEncryptedNEQ applies the NEQ predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldPublicTokenEncrypted, v))
}

// PublicTokenEncryptedIn applies the In predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldPublicTokenEncrypted, vs...))
}

// PublicTokenEncryptedNotIn applies the NotIn predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldPublicTokenEncrypted, vs...))
}

// PublicTokenEncryptedGT applies the GT predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldPublicTokenEncrypted, v))
}

// PublicTokenEncryptedGTE applies the GTE predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldPublicTokenEncrypted, v))
}

// PublicTokenEncryptedLT applies the LT predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldPublicTokenEncrypted, v))
}

// PublicTokenEncryptedLTE applies the LTE predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldPublicTokenEncrypted, v))
}

// PublicTokenEncryptedContains applies the Contains predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldPublicTokenEncrypted, v))
}

// PublicTokenEncryptedHasPrefix applies the HasPrefix predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldPublicTokenEncrypted, v))
}

// PublicTokenEncryptedHasSuffix applies the HasSuffix predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldPublicTokenEncrypted, v))
}

// PublicTokenEncryptedIsNil applies the IsNil predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedIsNil() predicate.Share {
	return predicate.Share(sql.FieldIsNull(FieldPublicTokenEncrypted))
}

// PublicTokenEncryptedNotNil applies the NotNil predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedNotNil() predicate.Share {
	return predicate.Share(sql.FieldNotNull(FieldPublicTokenEncrypted))
}

// PublicTokenEncryptedEqualFold applies the EqualFold predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldPublicTokenEncrypted, v))
}

// PublicTokenEncryptedContainsFold applies the ContainsFold predicate on the "public_token_encrypted" field.
func PublicTokenEncryptedContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldPublicTokenEncrypted, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldTokenHash, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashIsNil applies the IsNil predicate on the "password_hash" field.
func PasswordHashIsNil() predicate.Share {
	return predicate.Share(sql.FieldIsNull(FieldPasswordHash))
}

// PasswordHashNotNil applies the NotNil predicate on the "password_hash" field.
func PasswordHashNotNil() predicate.Share {
	return predicate.Share(sql.FieldNotNull(FieldPasswordHash))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldPasswordHash, v))
}

// UnlockVersionEQ applies the EQ predicate on the "unlock_version" field.
func UnlockVersionEQ(v int) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldUnlockVersion, v))
}

// UnlockVersionNEQ applies the NEQ predicate on the "unlock_version" field.
func UnlockVersionNEQ(v int) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldUnlockVersion, v))
}

// UnlockVersionIn applies the In predicate on the "unlock_version" field.
func UnlockVersionIn(vs ...int) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldUnlockVersion, vs...))
}

// UnlockVersionNotIn applies the NotIn predicate on the "unlock_version" field.
func UnlockVersionNotIn(vs ...int) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldUnlockVersion, vs...))
}

// UnlockVersionGT applies the GT predicate on the "unlock_version" field.
func UnlockVersionGT(v int) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldUnlockVersion, v))
}

// UnlockVersionGTE applies the GTE predicate on the "unlock_version" field.
func UnlockVersionGTE(v int) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldUnlockVersion, v))
}

// UnlockVersionLT applies the LT predicate on the "unlock_version" field.
func UnlockVersionLT(v int) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldUnlockVersion, v))
}

// UnlockVersionLTE applies the LTE predicate on the "unlock_version" field.
func UnlockVersionLTE(v int) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldUnlockVersion, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldTitle, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.Share {
	return predicate.Share(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.Share {
	return predicate.Share(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldNote, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldCreatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Share {
	return predicate.Share(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Share {
	return predicate.Share(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFiles applies the HasEdge predicate on the "files" edge.
func HasFiles() predicate.Share {
	return predicate.Share(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FilesTable, FilesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFilesWith applies the HasEdge predicate on the "files" edge with a given conditions (other predicates).
func HasFilesWith(preds ...predicate.File) predicate.Share {
	return predicate.Share(func(s *sql.Selector) {
		step := newFilesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Share) predicate.Share {
	return predicate.Share(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Share) predicate.Share {
	return predicate.Share(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Share) predicate.Share {
	return predicate.Share(sql.NotPredicates(p))
}
