// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BlobsColumns holds the columns for the "blobs" table.
	BlobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "size", Type: field.TypeInt64},
		{Name: "storage_path", Type: field.TypeString},
		{Name: "unreachable_since", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime},
	}
	// BlobsTable holds the schema information for the "blobs" table.
	BlobsTable = &schema.Table{
		Name:       "blobs",
		Columns:    BlobsColumns,
		PrimaryKey: []*schema.Column{BlobsColumns[0]},
	}
	// FilesColumns holds the columns for the "files" table.
	FilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "original_name", Type: field.TypeString},
		{Name: "upload_session_id", Type: field.TypeUUID, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "missing", "deleted"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "blob_files", Type: field.TypeString},
		{Name: "share_files", Type: field.TypeUUID},
	}
	// FilesTable holds the schema information for the "files" table.
	FilesTable = &schema.Table{
		Name:       "files",
		Columns:    FilesColumns,
		PrimaryKey: []*schema.Column{FilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "files_blobs_files",
				Columns:    []*schema.Column{FilesColumns[5]},
				RefColumns: []*schema.Column{BlobsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "files_shares_files",
				Columns:    []*schema.Column{FilesColumns[6]},
				RefColumns: []*schema.Column{SharesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SharesColumns holds the columns for the "shares" table.
	SharesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"download", "upload"}, Default: "download"},
		{Name: "public_token_encrypted", Type: field.TypeString, Nullable: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "unlock_version", Type: field.TypeInt, Default: 1},
		{Name: "title", Type: field.TypeString, Default: "Legacy Share"},
		{Name: "note", Type: field.TypeString, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "owner_id", Type: field.TypeUUID, Nullable: true},
	}
	// SharesTable holds the schema information for the "shares" table.
	SharesTable = &schema.Table{
		Name:       "shares",
		Columns:    SharesColumns,
		PrimaryKey: []*schema.Column{SharesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "shares_users_shares",
				Columns:    []*schema.Column{SharesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "auth_source", Type: field.TypeEnum, Enums: []string{"local", "ldap"}, Default: "local"},
		{Name: "auth_realm", Type: field.TypeString, Nullable: true},
		{Name: "external_id", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "can_manage_all_shares", Type: field.TypeBool, Default: false},
		{Name: "can_manage_users", Type: field.TypeBool, Default: false},
		{Name: "disabled", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BlobsTable,
		FilesTable,
		SharesTable,
		UsersTable,
	}
)

func init() {
	FilesTable.ForeignKeys[0].RefTable = BlobsTable
	FilesTable.ForeignKeys[1].RefTable = SharesTable
	SharesTable.ForeignKeys[0].RefTable = UsersTable
}
