// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kakra/ferry/ent/blob"
	"github.com/kakra/ferry/ent/file"
	"github.com/kakra/ferry/ent/predicate"
)

// BlobUpdate is the builder for updating Blob entities.
type BlobUpdate struct {
	config
	hooks    []Hook
	mutation *BlobMutation
}

// Where appends a list predicates to the BlobUpdate builder.
func (_u *BlobUpdate) Where(ps ...predicate.Blob) *BlobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSize sets the "size" field.
func (_u *BlobUpdate) SetSize(v int64) *BlobUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *BlobUpdate) SetNillableSize(v *int64) *BlobUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *BlobUpdate) AddSize(v int64) *BlobUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetStoragePath sets the "storage_path" field.
func (_u *BlobUpdate) SetStoragePath(v string) *BlobUpdate {
	_u.mutation.SetStoragePath(v)
	return _u
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_u *BlobUpdate) SetNillableStoragePath(v *string) *BlobUpdate {
	if v != nil {
		_u.SetStoragePath(*v)
	}
	return _u
}

// SetUnreachableSince sets the "unreachable_since" field.
func (_u *BlobUpdate) SetUnreachableSince(v time.Time) *BlobUpdate {
	_u.mutation.SetUnreachableSince(v)
	return _u
}

// SetNillableUnreachableSince sets the "unreachable_since" field if the given value is not nil.
func (_u *BlobUpdate) SetNillableUnreachableSince(v *time.Time) *BlobUpdate {
	if v != nil {
		_u.SetUnreachableSince(*v)
	}
	return _u
}

// ClearUnreachableSince clears the value of the "unreachable_since" field.
func (_u *BlobUpdate) ClearUnreachableSince() *BlobUpdate {
	_u.mutation.ClearUnreachableSince()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *BlobUpdate) SetLastSeenAt(v time.Time) *BlobUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *BlobUpdate) SetNillableLastSeenAt(v *time.Time) *BlobUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (_u *BlobUpdate) AddFileIDs(ids ...uuid.UUID) *BlobUpdate {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the File entity.
func (_u *BlobUpdate) AddFiles(v ...*File) *BlobUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the BlobMutation object of the builder.
func (_u *BlobUpdate) Mutation() *BlobMutation {
	return _u.mutation
}

// ClearFiles clears all "files" edges to the File entity.
func (_u *BlobUpdate) ClearFiles() *BlobUpdate {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (_u *BlobUpdate) RemoveFileIDs(ids ...uuid.UUID) *BlobUpdate {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to File entities.
func (_u *BlobUpdate) RemoveFiles(v ...*File) *BlobUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BlobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BlobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BlobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(blob.Table, blob.Columns, sqlgraph.NewFieldSpec(blob.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(blob.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(blob.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StoragePath(); ok {
		_spec.SetField(blob.FieldStoragePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnreachableSince(); ok {
		_spec.SetField(blob.FieldUnreachableSince, field.TypeTime, value)
	}
	if _u.mutation.UnreachableSinceCleared() {
		_spec.ClearField(blob.FieldUnreachableSince, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(blob.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   blob.FilesTable,
			Columns: []string{blob.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   blob.FilesTable,
			Columns: []string{blob.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   blob.FilesTable,
			Columns: []string{blob.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BlobUpdateOne is the builder for updating a single Blob entity.
type BlobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BlobMutation
}

// SetSize sets the "size" field.
func (_u *BlobUpdateOne) SetSize(v int64) *BlobUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *BlobUpdateOne) SetNillableSize(v *int64) *BlobUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *BlobUpdateOne) AddSize(v int64) *BlobUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetStoragePath sets the "storage_path" field.
func (_u *BlobUpdateOne) SetStoragePath(v string) *BlobUpdateOne {
	_u.mutation.SetStoragePath(v)
	return _u
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_u *BlobUpdateOne) SetNillableStoragePath(v *string) *BlobUpdateOne {
	if v != nil {
		_u.SetStoragePath(*v)
	}
	return _u
}

// SetUnreachableSince sets the "unreachable_since" field.
func (_u *BlobUpdateOne) SetUnreachableSince(v time.Time) *BlobUpdateOne {
	_u.mutation.SetUnreachableSince(v)
	return _u
}

// SetNillableUnreachableSince sets the "unreachable_since" field if the given value is not nil.
func (_u *BlobUpdateOne) SetNillableUnreachableSince(v *time.Time) *BlobUpdateOne {
	if v != nil {
		_u.SetUnreachableSince(*v)
	}
	return _u
}

// ClearUnreachableSince clears the value of the "unreachable_since" field.
func (_u *BlobUpdateOne) ClearUnreachableSince() *BlobUpdateOne {
	_u.mutation.ClearUnreachableSince()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *BlobUpdateOne) SetLastSeenAt(v time.Time) *BlobUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *BlobUpdateOne) SetNillableLastSeenAt(v *time.Time) *BlobUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (_u *BlobUpdateOne) AddFileIDs(ids ...uuid.UUID) *BlobUpdateOne {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the File entity.
func (_u *BlobUpdateOne) AddFiles(v ...*File) *BlobUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the BlobMutation object of the builder.
func (_u *BlobUpdateOne) Mutation() *BlobMutation {
	return _u.mutation
}

// ClearFiles clears all "files" edges to the File entity.
func (_u *BlobUpdateOne) ClearFiles() *BlobUpdateOne {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (_u *BlobUpdateOne) RemoveFileIDs(ids ...uuid.UUID) *BlobUpdateOne {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to File entities.
func (_u *BlobUpdateOne) RemoveFiles(v ...*File) *BlobUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Where appends a list predicates to the BlobUpdate builder.
func (_u *BlobUpdateOne) Where(ps ...predicate.Blob) *BlobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BlobUpdateOne) Select(field string, fields ...string) *BlobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Blob entity.
func (_u *BlobUpdateOne) Save(ctx context.Context) (*Blob, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlobUpdateOne) SaveX(ctx context.Context) *Blob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BlobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BlobUpdateOne) sqlSave(ctx context.Context) (_node *Blob, err error) {
	_spec := sqlgraph.NewUpdateSpec(blob.Table, blob.Columns, sqlgraph.NewFieldSpec(blob.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Blob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blob.FieldID)
		for _, f := range fields {
			if !blob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != blob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(blob.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(blob.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StoragePath(); ok {
		_spec.SetField(blob.FieldStoragePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnreachableSince(); ok {
		_spec.SetField(blob.FieldUnreachableSince, field.TypeTime, value)
	}
	if _u.mutation.UnreachableSinceCleared() {
		_spec.ClearField(blob.FieldUnreachableSince, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(blob.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   blob.FilesTable,
			Columns: []string{blob.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   blob.FilesTable,
			Columns: []string{blob.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   blob.FilesTable,
			Columns: []string{blob.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Blob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
