// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kakra/ferry/ent/blob"
	"github.com/kakra/ferry/ent/file"
	"github.com/kakra/ferry/ent/predicate"
	"github.com/kakra/ferry/ent/share"
)

// FileUpdate is the builder for updating File entities.
type FileUpdate struct {
	config
	hooks    []Hook
	mutation *FileMutation
}

// Where appends a list predicates to the FileUpdate builder.
func (_u *FileUpdate) Where(ps ...predicate.File) *FileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOriginalName sets the "original_name" field.
func (_u *FileUpdate) SetOriginalName(v string) *FileUpdate {
	_u.mutation.SetOriginalName(v)
	return _u
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (_u *FileUpdate) SetNillableOriginalName(v *string) *FileUpdate {
	if v != nil {
		_u.SetOriginalName(*v)
	}
	return _u
}

// SetUploadSessionID sets the "upload_session_id" field.
func (_u *FileUpdate) SetUploadSessionID(v uuid.UUID) *FileUpdate {
	_u.mutation.SetUploadSessionID(v)
	return _u
}

// SetNillableUploadSessionID sets the "upload_session_id" field if the given value is not nil.
func (_u *FileUpdate) SetNillableUploadSessionID(v *uuid.UUID) *FileUpdate {
	if v != nil {
		_u.SetUploadSessionID(*v)
	}
	return _u
}

// ClearUploadSessionID clears the value of the "upload_session_id" field.
func (_u *FileUpdate) ClearUploadSessionID() *FileUpdate {
	_u.mutation.ClearUploadSessionID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *FileUpdate) SetStatus(v file.Status) *FileUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FileUpdate) SetNillableStatus(v *file.Status) *FileUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBlobID sets the "blob" edge to the Blob entity by ID.
func (_u *FileUpdate) SetBlobID(id string) *FileUpdate {
	_u.mutation.SetBlobID(id)
	return _u
}

// SetBlob sets the "blob" edge to the Blob entity.
func (_u *FileUpdate) SetBlob(v *Blob) *FileUpdate {
	return _u.SetBlobID(v.ID)
}

// SetShareID sets the "share" edge to the Share entity by ID.
func (_u *FileUpdate) SetShareID(id uuid.UUID) *FileUpdate {
	_u.mutation.SetShareID(id)
	return _u
}

// SetShare sets the "share" edge to the Share entity.
func (_u *FileUpdate) SetShare(v *Share) *FileUpdate {
	return _u.SetShareID(v.ID)
}

// Mutation returns the FileMutation object of the builder.
func (_u *FileUpdate) Mutation() *FileMutation {
	return _u.mutation
}

// ClearBlob clears the "blob" edge to the Blob entity.
func (_u *FileUpdate) ClearBlob() *FileUpdate {
	_u.mutation.ClearBlob()
	return _u
}

// ClearShare clears the "share" edge to the Share entity.
func (_u *FileUpdate) ClearShare() *FileUpdate {
	_u.mutation.ClearShare()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := file.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "File.status": %w`, err)}
		}
	}
	if _u.mutation.BlobCleared() && len(_u.mutation.BlobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "File.blob"`)
	}
	if _u.mutation.ShareCleared() && len(_u.mutation.ShareIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "File.share"`)
	}
	return nil
}

func (_u *FileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(file.Table, file.Columns, sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OriginalName(); ok {
		_spec.SetField(file.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UploadSessionID(); ok {
		_spec.SetField(file.FieldUploadSessionID, field.TypeUUID, value)
	}
	if _u.mutation.UploadSessionIDCleared() {
		_spec.ClearField(file.FieldUploadSessionID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(file.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.BlobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.BlobTable,
			Columns: []string{file.BlobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blob.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.BlobTable,
			Columns: []string{file.BlobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ShareCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.ShareTable,
			Columns: []string{file.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShareIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.ShareTable,
			Columns: []string{file.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{file.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FileUpdateOne is the builder for updating a single File entity.
type FileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FileMutation
}

// SetOriginalName sets the "original_name" field.
func (_u *FileUpdateOne) SetOriginalName(v string) *FileUpdateOne {
	_u.mutation.SetOriginalName(v)
	return _u
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableOriginalName(v *string) *FileUpdateOne {
	if v != nil {
		_u.SetOriginalName(*v)
	}
	return _u
}

// SetUploadSessionID sets the "upload_session_id" field.
func (_u *FileUpdateOne) SetUploadSessionID(v uuid.UUID) *FileUpdateOne {
	_u.mutation.SetUploadSessionID(v)
	return _u
}

// SetNillableUploadSessionID sets the "upload_session_id" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableUploadSessionID(v *uuid.UUID) *FileUpdateOne {
	if v != nil {
		_u.SetUploadSessionID(*v)
	}
	return _u
}

// ClearUploadSessionID clears the value of the "upload_session_id" field.
func (_u *FileUpdateOne) ClearUploadSessionID() *FileUpdateOne {
	_u.mutation.ClearUploadSessionID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *FileUpdateOne) SetStatus(v file.Status) *FileUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FileUpdateOne) SetNillableStatus(v *file.Status) *FileUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBlobID sets the "blob" edge to the Blob entity by ID.
func (_u *FileUpdateOne) SetBlobID(id string) *FileUpdateOne {
	_u.mutation.SetBlobID(id)
	return _u
}

// SetBlob sets the "blob" edge to the Blob entity.
func (_u *FileUpdateOne) SetBlob(v *Blob) *FileUpdateOne {
	return _u.SetBlobID(v.ID)
}

// SetShareID sets the "share" edge to the Share entity by ID.
func (_u *FileUpdateOne) SetShareID(id uuid.UUID) *FileUpdateOne {
	_u.mutation.SetShareID(id)
	return _u
}

// SetShare sets the "share" edge to the Share entity.
func (_u *FileUpdateOne) SetShare(v *Share) *FileUpdateOne {
	return _u.SetShareID(v.ID)
}

// Mutation returns the FileMutation object of the builder.
func (_u *FileUpdateOne) Mutation() *FileMutation {
	return _u.mutation
}

// ClearBlob clears the "blob" edge to the Blob entity.
func (_u *FileUpdateOne) ClearBlob() *FileUpdateOne {
	_u.mutation.ClearBlob()
	return _u
}

// ClearShare clears the "share" edge to the Share entity.
func (_u *FileUpdateOne) ClearShare() *FileUpdateOne {
	_u.mutation.ClearShare()
	return _u
}

// Where appends a list predicates to the FileUpdate builder.
func (_u *FileUpdateOne) Where(ps ...predicate.File) *FileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FileUpdateOne) Select(field string, fields ...string) *FileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated File entity.
func (_u *FileUpdateOne) Save(ctx context.Context) (*File, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileUpdateOne) SaveX(ctx context.Context) *File {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := file.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "File.status": %w`, err)}
		}
	}
	if _u.mutation.BlobCleared() && len(_u.mutation.BlobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "File.blob"`)
	}
	if _u.mutation.ShareCleared() && len(_u.mutation.ShareIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "File.share"`)
	}
	return nil
}

func (_u *FileUpdateOne) sqlSave(ctx context.Context) (_node *File, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(file.Table, file.Columns, sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "File.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, file.FieldID)
		for _, f := range fields {
			if !file.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != file.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OriginalName(); ok {
		_spec.SetField(file.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UploadSessionID(); ok {
		_spec.SetField(file.FieldUploadSessionID, field.TypeUUID, value)
	}
	if _u.mutation.UploadSessionIDCleared() {
		_spec.ClearField(file.FieldUploadSessionID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(file.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.BlobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.BlobTable,
			Columns: []string{file.BlobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blob.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.BlobTable,
			Columns: []string{file.BlobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blob.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ShareCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.ShareTable,
			Columns: []string{file.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShareIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.ShareTable,
			Columns: []string{file.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &File{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{file.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
