// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/kakra/ferry/ent/blob"
	"github.com/kakra/ferry/ent/file"
	"github.com/kakra/ferry/ent/schema"
	"github.com/kakra/ferry/ent/share"
	"github.com/kakra/ferry/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blobFields := schema.Blob{}.Fields()
	_ = blobFields
	// blobDescCreatedAt is the schema descriptor for created_at field.
	blobDescCreatedAt := blobFields[4].Descriptor()
	// blob.DefaultCreatedAt holds the default value on creation for the created_at field.
	blob.DefaultCreatedAt = blobDescCreatedAt.Default.(func() time.Time)
	// blobDescLastSeenAt is the schema descriptor for last_seen_at field.
	blobDescLastSeenAt := blobFields[5].Descriptor()
	// blob.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	blob.DefaultLastSeenAt = blobDescLastSeenAt.Default.(func() time.Time)
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescCreatedAt is the schema descriptor for created_at field.
	fileDescCreatedAt := fileFields[4].Descriptor()
	// file.DefaultCreatedAt holds the default value on creation for the created_at field.
	file.DefaultCreatedAt = fileDescCreatedAt.Default.(func() time.Time)
	// fileDescID is the schema descriptor for id field.
	fileDescID := fileFields[0].Descriptor()
	// file.DefaultID holds the default value on creation for the id field.
	file.DefaultID = fileDescID.Default.(func() uuid.UUID)
	shareFields := schema.Share{}.Fields()
	_ = shareFields
	// shareDescUnlockVersion is the schema descriptor for unlock_version field.
	shareDescUnlockVersion := shareFields[6].Descriptor()
	// share.DefaultUnlockVersion holds the default value on creation for the unlock_version field.
	share.DefaultUnlockVersion = shareDescUnlockVersion.Default.(int)
	// shareDescTitle is the schema descriptor for title field.
	shareDescTitle := shareFields[7].Descriptor()
	// share.DefaultTitle holds the default value on creation for the title field.
	share.DefaultTitle = shareDescTitle.Default.(string)
	// share.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	share.TitleValidator = shareDescTitle.Validators[0].(func(string) error)
	// shareDescCreatedAt is the schema descriptor for created_at field.
	shareDescCreatedAt := shareFields[10].Descriptor()
	// share.DefaultCreatedAt holds the default value on creation for the created_at field.
	share.DefaultCreatedAt = shareDescCreatedAt.Default.(func() time.Time)
	// shareDescID is the schema descriptor for id field.
	shareDescID := shareFields[0].Descriptor()
	// share.DefaultID holds the default value on creation for the id field.
	share.DefaultID = shareDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[6].Descriptor()
	// user.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	user.DisplayNameValidator = userDescDisplayName.Validators[0].(func(string) error)
	// userDescCanManageAllShares is the schema descriptor for can_manage_all_shares field.
	userDescCanManageAllShares := userFields[8].Descriptor()
	// user.DefaultCanManageAllShares holds the default value on creation for the can_manage_all_shares field.
	user.DefaultCanManageAllShares = userDescCanManageAllShares.Default.(bool)
	// userDescCanManageUsers is the schema descriptor for can_manage_users field.
	userDescCanManageUsers := userFields[9].Descriptor()
	// user.DefaultCanManageUsers holds the default value on creation for the can_manage_users field.
	user.DefaultCanManageUsers = userDescCanManageUsers.Default.(bool)
	// userDescDisabled is the schema descriptor for disabled field.
	userDescDisabled := userFields[10].Descriptor()
	// user.DefaultDisabled holds the default value on creation for the disabled field.
	user.DefaultDisabled = userDescDisabled.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[11].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[12].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
