// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kakra/ferry/ent/file"
	"github.com/kakra/ferry/ent/predicate"
	"github.com/kakra/ferry/ent/share"
	"github.com/kakra/ferry/ent/user"
)

// ShareUpdate is the builder for updating Share entities.
type ShareUpdate struct {
	config
	hooks    []Hook
	mutation *ShareMutation
}

// Where appends a list predicates to the ShareUpdate builder.
func (_u *ShareUpdate) Where(ps ...predicate.Share) *ShareUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *ShareUpdate) SetOwnerID(v uuid.UUID) *ShareUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableOwnerID(v *uuid.UUID) *ShareUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (_u *ShareUpdate) ClearOwnerID() *ShareUpdate {
	_u.mutation.ClearOwnerID()
	return _u
}

// SetType sets the "type" field.
func (_u *ShareUpdate) SetType(v share.Type) *ShareUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableType(v *share.Type) *ShareUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPublicTokenEncrypted sets the "public_token_encrypted" field.
func (_u *ShareUpdate) SetPublicTokenEncrypted(v string) *ShareUpdate {
	_u.mutation.SetPublicTokenEncrypted(v)
	return _u
}

// SetNillablePublicTokenEncrypted sets the "public_token_encrypted" field if the given value is not nil.
func (_u *ShareUpdate) SetNillablePublicTokenEncrypted(v *string) *ShareUpdate {
	if v != nil {
		_u.SetPublicTokenEncrypted(*v)
	}
	return _u
}

// ClearPublicTokenEncrypted clears the value of the "public_token_encrypted" field.
func (_u *ShareUpdate) ClearPublicTokenEncrypted() *ShareUpdate {
	_u.mutation.ClearPublicTokenEncrypted()
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *ShareUpdate) SetTokenHash(v string) *ShareUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableTokenHash(v *string) *ShareUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *ShareUpdate) SetPasswordHash(v string) *ShareUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *ShareUpdate) SetNillablePasswordHash(v *string) *ShareUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *ShareUpdate) ClearPasswordHash() *ShareUpdate {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetUnlockVersion sets the "unlock_version" field.
func (_u *ShareUpdate) SetUnlockVersion(v int) *ShareUpdate {
	_u.mutation.ResetUnlockVersion()
	_u.mutation.SetUnlockVersion(v)
	return _u
}

// SetNillableUnlockVersion sets the "unlock_version" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableUnlockVersion(v *int) *ShareUpdate {
	if v != nil {
		_u.SetUnlockVersion(*v)
	}
	return _u
}

// AddUnlockVersion adds value to the "unlock_version" field.
func (_u *ShareUpdate) AddUnlockVersion(v int) *ShareUpdate {
	_u.mutation.AddUnlockVersion(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ShareUpdate) SetTitle(v string) *ShareUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableTitle(v *string) *ShareUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *ShareUpdate) SetNote(v string) *ShareUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableNote(v *string) *ShareUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *ShareUpdate) ClearNote() *ShareUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ShareUpdate) SetExpiresAt(v time.Time) *ShareUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableExpiresAt(v *time.Time) *ShareUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ShareUpdate) SetCreatedAt(v time.Time) *ShareUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableCreatedAt(v *time.Time) *ShareUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ShareUpdate) SetOwner(v *User) *ShareUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (_u *ShareUpdate) AddFileIDs(ids ...uuid.UUID) *ShareUpdate {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the File entity.
func (_u *ShareUpdate) AddFiles(v ...*File) *ShareUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the ShareMutation object of the builder.
func (_u *ShareUpdate) Mutation() *ShareMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ShareUpdate) ClearOwner() *ShareUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearFiles clears all "files" edges to the File entity.
func (_u *ShareUpdate) ClearFiles() *ShareUpdate {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (_u *ShareUpdate) RemoveFileIDs(ids ...uuid.UUID) *ShareUpdate {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to File entities.
func (_u *ShareUpdate) RemoveFiles(v ...*File) *ShareUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ShareUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShareUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ShareUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShareUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ShareUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := share.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Share.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := share.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Share.title": %w`, err)}
		}
	}
	return nil
}

func (_u *ShareUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(share.Table, share.Columns, sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(share.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PublicTokenEncrypted(); ok {
		_spec.SetField(share.FieldPublicTokenEncrypted, field.TypeString, value)
	}
	if _u.mutation.PublicTokenEncryptedCleared() {
		_spec.ClearField(share.FieldPublicTokenEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(share.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(share.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(share.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.UnlockVersion(); ok {
		_spec.SetField(share.FieldUnlockVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUnlockVersion(); ok {
		_spec.AddField(share.FieldUnlockVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(share.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(share.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(share.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(share.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(share.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.OwnerTable,
			Columns: []string{share.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.OwnerTable,
			Columns: []string{share.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   share.FilesTable,
			Columns: []string{share.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   share.FilesTable,
			Columns: []string{share.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   share.FilesTable,
			Columns: []string{share.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{share.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ShareUpdateOne is the builder for updating a single Share entity.
type ShareUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShareMutation
}

// SetOwnerID sets the "owner_id" field.
func (_u *ShareUpdateOne) SetOwnerID(v uuid.UUID) *ShareUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableOwnerID(v *uuid.UUID) *ShareUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// ClearOwnerID clears the value of the "owner_id" field.
func (_u *ShareUpdateOne) ClearOwnerID() *ShareUpdateOne {
	_u.mutation.ClearOwnerID()
	return _u
}

// SetType sets the "type" field.
func (_u *ShareUpdateOne) SetType(v share.Type) *ShareUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableType(v *share.Type) *ShareUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPublicTokenEncrypted sets the "public_token_encrypted" field.
func (_u *ShareUpdateOne) SetPublicTokenEncrypted(v string) *ShareUpdateOne {
	_u.mutation.SetPublicTokenEncrypted(v)
	return _u
}

// SetNillablePublicTokenEncrypted sets the "public_token_encrypted" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillablePublicTokenEncrypted(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetPublicTokenEncrypted(*v)
	}
	return _u
}

// ClearPublicTokenEncrypted clears the value of the "public_token_encrypted" field.
func (_u *ShareUpdateOne) ClearPublicTokenEncrypted() *ShareUpdateOne {
	_u.mutation.ClearPublicTokenEncrypted()
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *ShareUpdateOne) SetTokenHash(v string) *ShareUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableTokenHash(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *ShareUpdateOne) SetPasswordHash(v string) *ShareUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillablePasswordHash(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *ShareUpdateOne) ClearPasswordHash() *ShareUpdateOne {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetUnlockVersion sets the "unlock_version" field.
func (_u *ShareUpdateOne) SetUnlockVersion(v int) *ShareUpdateOne {
	_u.mutation.ResetUnlockVersion()
	_u.mutation.SetUnlockVersion(v)
	return _u
}

// SetNillableUnlockVersion sets the "unlock_version" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableUnlockVersion(v *int) *ShareUpdateOne {
	if v != nil {
		_u.SetUnlockVersion(*v)
	}
	return _u
}

// AddUnlockVersion adds value to the "unlock_version" field.
func (_u *ShareUpdateOne) AddUnlockVersion(v int) *ShareUpdateOne {
	_u.mutation.AddUnlockVersion(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ShareUpdateOne) SetTitle(v string) *ShareUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableTitle(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *ShareUpdateOne) SetNote(v string) *ShareUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableNote(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *ShareUpdateOne) ClearNote() *ShareUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ShareUpdateOne) SetExpiresAt(v time.Time) *ShareUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableExpiresAt(v *time.Time) *ShareUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ShareUpdateOne) SetCreatedAt(v time.Time) *ShareUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableCreatedAt(v *time.Time) *ShareUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ShareUpdateOne) SetOwner(v *User) *ShareUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (_u *ShareUpdateOne) AddFileIDs(ids ...uuid.UUID) *ShareUpdateOne {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the File entity.
func (_u *ShareUpdateOne) AddFiles(v ...*File) *ShareUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the ShareMutation object of the builder.
func (_u *ShareUpdateOne) Mutation() *ShareMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ShareUpdateOne) ClearOwner() *ShareUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearFiles clears all "files" edges to the File entity.
func (_u *ShareUpdateOne) ClearFiles() *ShareUpdateOne {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (_u *ShareUpdateOne) RemoveFileIDs(ids ...uuid.UUID) *ShareUpdateOne {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to File entities.
func (_u *ShareUpdateOne) RemoveFiles(v ...*File) *ShareUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Where appends a list predicates to the ShareUpdate builder.
func (_u *ShareUpdateOne) Where(ps ...predicate.Share) *ShareUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ShareUpdateOne) Select(field string, fields ...string) *ShareUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Share entity.
func (_u *ShareUpdateOne) Save(ctx context.Context) (*Share, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShareUpdateOne) SaveX(ctx context.Context) *Share {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ShareUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShareUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ShareUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := share.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Share.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := share.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Share.title": %w`, err)}
		}
	}
	return nil
}

func (_u *ShareUpdateOne) sqlSave(ctx context.Context) (_node *Share, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(share.Table, share.Columns, sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Share.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, share.FieldID)
		for _, f := range fields {
			if !share.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != share.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(share.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PublicTokenEncrypted(); ok {
		_spec.SetField(share.FieldPublicTokenEncrypted, field.TypeString, value)
	}
	if _u.mutation.PublicTokenEncryptedCleared() {
		_spec.ClearField(share.FieldPublicTokenEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(share.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(share.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(share.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.UnlockVersion(); ok {
		_spec.SetField(share.FieldUnlockVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUnlockVersion(); ok {
		_spec.AddField(share.FieldUnlockVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(share.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(share.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(share.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(share.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(share.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.OwnerTable,
			Columns: []string{share.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.OwnerTable,
			Columns: []string{share.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   share.FilesTable,
			Columns: []string{share.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   share.FilesTable,
			Columns: []string{share.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   share.FilesTable,
			Columns: []string{share.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Share{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{share.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
