// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kakra/ferry/ent/file"
	"github.com/kakra/ferry/ent/share"
	"github.com/kakra/ferry/ent/user"
)

// ShareCreate is the builder for creating a Share entity.
type ShareCreate struct {
	config
	mutation *ShareMutation
	hooks    []Hook
}

// SetOwnerID sets the "owner_id" field.
func (_c *ShareCreate) SetOwnerID(v uuid.UUID) *ShareCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_c *ShareCreate) SetNillableOwnerID(v *uuid.UUID) *ShareCreate {
	if v != nil {
		_c.SetOwnerID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *ShareCreate) SetType(v share.Type) *ShareCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ShareCreate) SetNillableType(v *share.Type) *ShareCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetPublicTokenEncrypted sets the "public_token_encrypted" field.
func (_c *ShareCreate) SetPublicTokenEncrypted(v string) *ShareCreate {
	_c.mutation.SetPublicTokenEncrypted(v)
	return _c
}

// SetNillablePublicTokenEncrypted sets the "public_token_encrypted" field if the given value is not nil.
func (_c *ShareCreate) SetNillablePublicTokenEncrypted(v *string) *ShareCreate {
	if v != nil {
		_c.SetPublicTokenEncrypted(*v)
	}
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *ShareCreate) SetTokenHash(v string) *ShareCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *ShareCreate) SetPasswordHash(v string) *ShareCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_c *ShareCreate) SetNillablePasswordHash(v *string) *ShareCreate {
	if v != nil {
		_c.SetPasswordHash(*v)
	}
	return _c
}

// SetUnlockVersion sets the "unlock_version" field.
func (_c *ShareCreate) SetUnlockVersion(v int) *ShareCreate {
	_c.mutation.SetUnlockVersion(v)
	return _c
}

// SetNillableUnlockVersion sets the "unlock_version" field if the given value is not nil.
func (_c *ShareCreate) SetNillableUnlockVersion(v *int) *ShareCreate {
	if v != nil {
		_c.SetUnlockVersion(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *ShareCreate) SetTitle(v string) *ShareCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *ShareCreate) SetNillableTitle(v *string) *ShareCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *ShareCreate) SetNote(v string) *ShareCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *ShareCreate) SetNillableNote(v *string) *ShareCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ShareCreate) SetExpiresAt(v time.Time) *ShareCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ShareCreate) SetCreatedAt(v time.Time) *ShareCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ShareCreate) SetNillableCreatedAt(v *time.Time) *ShareCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ShareCreate) SetID(v uuid.UUID) *ShareCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ShareCreate) SetNillableID(v *uuid.UUID) *ShareCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *ShareCreate) SetOwner(v *User) *ShareCreate {
	return _c.SetOwnerID(v.ID)
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (_c *ShareCreate) AddFileIDs(ids ...uuid.UUID) *ShareCreate {
	_c.mutation.AddFileIDs(ids...)
	return _c
}

// AddFiles adds the "files" edges to the File entity.
func (_c *ShareCreate) AddFiles(v ...*File) *ShareCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFileIDs(ids...)
}

// Mutation returns the ShareMutation object of the builder.
func (_c *ShareCreate) Mutation() *ShareMutation {
	return _c.mutation
}

// Save creates the Share in the database.
func (_c *ShareCreate) Save(ctx context.Context) (*Share, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShareCreate) SaveX(ctx context.Context) *Share {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShareCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShareCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShareCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := share.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.UnlockVersion(); !ok {
		v := share.DefaultUnlockVersion
		_c.mutation.SetUnlockVersion(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := share.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := share.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := share.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShareCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Share.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := share.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Share.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "Share.token_hash"`)}
	}
	if _, ok := _c.mutation.UnlockVersion(); !ok {
		return &ValidationError{Name: "unlock_version", err: errors.New(`ent: missing required field "Share.unlock_version"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Share.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := share.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Share.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "Share.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Share.created_at"`)}
	}
	return nil
}

func (_c *ShareCreate) sqlSave(ctx context.Context) (*Share, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShareCreate) createSpec() (*Share, *sqlgraph.CreateSpec) {
	var (
		_node = &Share{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(share.Table, sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(share.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.PublicTokenEncrypted(); ok {
		_spec.SetField(share.FieldPublicTokenEncrypted, field.TypeString, value)
		_node.PublicTokenEncrypted = &value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(share.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(share.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = &value
	}
	if value, ok := _c.mutation.UnlockVersion(); ok {
		_spec.SetField(share.FieldUnlockVersion, field.TypeInt, value)
		_node.UnlockVersion = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(share.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(share.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(share.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(share.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   share.OwnerTable,
			Columns: []string{share.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   share.FilesTable,
			Columns: []string{share.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ShareCreateBulk is the builder for creating many Share entities in bulk.
type ShareCreateBulk struct {
	config
	err      error
	builders []*ShareCreate
}

// Save creates the Share entities in the database.
func (_c *ShareCreateBulk) Save(ctx context.Context) ([]*Share, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Share, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShareMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShareCreateBulk) SaveX(ctx context.Context) []*Share {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShareCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShareCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
