// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kakra/ferry/ent/predicate"
	"github.com/kakra/ferry/ent/share"
	"github.com/kakra/ferry/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdate) SetUsername(v string) *UserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetAuthSource sets the "auth_source" field.
func (_u *UserUpdate) SetAuthSource(v user.AuthSource) *UserUpdate {
	_u.mutation.SetAuthSource(v)
	return _u
}

// SetNillableAuthSource sets the "auth_source" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAuthSource(v *user.AuthSource) *UserUpdate {
	if v != nil {
		_u.SetAuthSource(*v)
	}
	return _u
}

// SetAuthRealm sets the "auth_realm" field.
func (_u *UserUpdate) SetAuthRealm(v string) *UserUpdate {
	_u.mutation.SetAuthRealm(v)
	return _u
}

// SetNillableAuthRealm sets the "auth_realm" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAuthRealm(v *string) *UserUpdate {
	if v != nil {
		_u.SetAuthRealm(*v)
	}
	return _u
}

// ClearAuthRealm clears the value of the "auth_realm" field.
func (_u *UserUpdate) ClearAuthRealm() *UserUpdate {
	_u.mutation.ClearAuthRealm()
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *UserUpdate) SetExternalID(v string) *UserUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableExternalID(v *string) *UserUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *UserUpdate) ClearExternalID() *UserUpdate {
	_u.mutation.ClearExternalID()
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserUpdate) ClearEmail() *UserUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *UserUpdate) SetDisplayName(v string) *UserUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDisplayName(v *string) *UserUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *UserUpdate) ClearPasswordHash() *UserUpdate {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetCanManageAllShares sets the "can_manage_all_shares" field.
func (_u *UserUpdate) SetCanManageAllShares(v bool) *UserUpdate {
	_u.mutation.SetCanManageAllShares(v)
	return _u
}

// SetNillableCanManageAllShares sets the "can_manage_all_shares" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCanManageAllShares(v *bool) *UserUpdate {
	if v != nil {
		_u.SetCanManageAllShares(*v)
	}
	return _u
}

// SetCanManageUsers sets the "can_manage_users" field.
func (_u *UserUpdate) SetCanManageUsers(v bool) *UserUpdate {
	_u.mutation.SetCanManageUsers(v)
	return _u
}

// SetNillableCanManageUsers sets the "can_manage_users" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCanManageUsers(v *bool) *UserUpdate {
	if v != nil {
		_u.SetCanManageUsers(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *UserUpdate) SetDisabled(v bool) *UserUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDisabled(v *bool) *UserUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddShareIDs adds the "shares" edge to the Share entity by IDs.
func (_u *UserUpdate) AddShareIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddShareIDs(ids...)
	return _u
}

// AddShares adds the "shares" edges to the Share entity.
func (_u *UserUpdate) AddShares(v ...*Share) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShareIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearShares clears all "shares" edges to the Share entity.
func (_u *UserUpdate) ClearShares() *UserUpdate {
	_u.mutation.ClearShares()
	return _u
}

// RemoveShareIDs removes the "shares" edge to Share entities by IDs.
func (_u *UserUpdate) RemoveShareIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveShareIDs(ids...)
	return _u
}

// RemoveShares removes "shares" edges to Share entities.
func (_u *UserUpdate) RemoveShares(v ...*Share) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShareIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthSource(); ok {
		if err := user.AuthSourceValidator(v); err != nil {
			return &ValidationError{Name: "auth_source", err: fmt.Errorf(`ent: validator failed for field "User.auth_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := user.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "User.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthSource(); ok {
		_spec.SetField(user.FieldAuthSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuthRealm(); ok {
		_spec.SetField(user.FieldAuthRealm, field.TypeString, value)
	}
	if _u.mutation.AuthRealmCleared() {
		_spec.ClearField(user.FieldAuthRealm, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(user.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(user.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(user.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(user.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.CanManageAllShares(); ok {
		_spec.SetField(user.FieldCanManageAllShares, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CanManageUsers(); ok {
		_spec.SetField(user.FieldCanManageUsers, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(user.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SharesTable,
			Columns: []string{user.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSharesIDs(); len(nodes) > 0 && !_u.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SharesTable,
			Columns: []string{user.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SharesTable,
			Columns: []string{user.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUsername sets the "username" field.
func (_u *UserUpdateOne) SetUsername(v string) *UserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetAuthSource sets the "auth_source" field.
func (_u *UserUpdateOne) SetAuthSource(v user.AuthSource) *UserUpdateOne {
	_u.mutation.SetAuthSource(v)
	return _u
}

// SetNillableAuthSource sets the "auth_source" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAuthSource(v *user.AuthSource) *UserUpdateOne {
	if v != nil {
		_u.SetAuthSource(*v)
	}
	return _u
}

// SetAuthRealm sets the "auth_realm" field.
func (_u *UserUpdateOne) SetAuthRealm(v string) *UserUpdateOne {
	_u.mutation.SetAuthRealm(v)
	return _u
}

// SetNillableAuthRealm sets the "auth_realm" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAuthRealm(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAuthRealm(*v)
	}
	return _u
}

// ClearAuthRealm clears the value of the "auth_realm" field.
func (_u *UserUpdateOne) ClearAuthRealm() *UserUpdateOne {
	_u.mutation.ClearAuthRealm()
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *UserUpdateOne) SetExternalID(v string) *UserUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableExternalID(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *UserUpdateOne) ClearExternalID() *UserUpdateOne {
	_u.mutation.ClearExternalID()
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserUpdateOne) ClearEmail() *UserUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *UserUpdateOne) SetDisplayName(v string) *UserUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDisplayName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *UserUpdateOne) ClearPasswordHash() *UserUpdateOne {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetCanManageAllShares sets the "can_manage_all_shares" field.
func (_u *UserUpdateOne) SetCanManageAllShares(v bool) *UserUpdateOne {
	_u.mutation.SetCanManageAllShares(v)
	return _u
}

// SetNillableCanManageAllShares sets the "can_manage_all_shares" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCanManageAllShares(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetCanManageAllShares(*v)
	}
	return _u
}

// SetCanManageUsers sets the "can_manage_users" field.
func (_u *UserUpdateOne) SetCanManageUsers(v bool) *UserUpdateOne {
	_u.mutation.SetCanManageUsers(v)
	return _u
}

// SetNillableCanManageUsers sets the "can_manage_users" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCanManageUsers(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetCanManageUsers(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *UserUpdateOne) SetDisabled(v bool) *UserUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDisabled(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddShareIDs adds the "shares" edge to the Share entity by IDs.
func (_u *UserUpdateOne) AddShareIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddShareIDs(ids...)
	return _u
}

// AddShares adds the "shares" edges to the Share entity.
func (_u *UserUpdateOne) AddShares(v ...*Share) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShareIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearShares clears all "shares" edges to the Share entity.
func (_u *UserUpdateOne) ClearShares() *UserUpdateOne {
	_u.mutation.ClearShares()
	return _u
}

// RemoveShareIDs removes the "shares" edge to Share entities by IDs.
func (_u *UserUpdateOne) RemoveShareIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveShareIDs(ids...)
	return _u
}

// RemoveShares removes "shares" edges to Share entities.
func (_u *UserUpdateOne) RemoveShares(v ...*Share) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShareIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthSource(); ok {
		if err := user.AuthSourceValidator(v); err != nil {
			return &ValidationError{Name: "auth_source", err: fmt.Errorf(`ent: validator failed for field "User.auth_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := user.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "User.display_name": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthSource(); ok {
		_spec.SetField(user.FieldAuthSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuthRealm(); ok {
		_spec.SetField(user.FieldAuthRealm, field.TypeString, value)
	}
	if _u.mutation.AuthRealmCleared() {
		_spec.ClearField(user.FieldAuthRealm, field.TypeString)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(user.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(user.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(user.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(user.FieldPasswordHash, field.TypeString)
	}
	if value, ok := _u.mutation.CanManageAllShares(); ok {
		_spec.SetField(user.FieldCanManageAllShares, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CanManageUsers(); ok {
		_spec.SetField(user.FieldCanManageUsers, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(user.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SharesTable,
			Columns: []string{user.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSharesIDs(); len(nodes) > 0 && !_u.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SharesTable,
			Columns: []string{user.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SharesTable,
			Columns: []string{user.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
