// Code generated by ent, DO NOT EDIT.

package blob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/kakra/ferry/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Blob {
	return predicate.Blob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Blob {
	return predicate.Blob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Blob {
	return predicate.Blob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Blob {
	return predicate.Blob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Blob {
	return predicate.Blob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Blob {
	return predicate.Blob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Blob {
	return predicate.Blob(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Blob {
	return predicate.Blob(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Blob {
	return predicate.Blob(sql.FieldContainsFold(FieldID, id))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldSize, v))
}

// StoragePath applies equality check predicate on the "storage_path" field. It's identical to StoragePathEQ.
func StoragePath(v string) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldStoragePath, v))
}

// UnreachableSince applies equality check predicate on the "unreachable_since" field. It's identical to UnreachableSinceEQ.
func UnreachableSince(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldUnreachableSince, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldCreatedAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldLastSeenAt, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.Blob {
	return predicate.Blob(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.Blob {
	return predicate.Blob(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.Blob {
	return predicate.Blob(sql.FieldLTE(FieldSize, v))
}

// StoragePathEQ applies the EQ predicate on the "storage_path" field.
func StoragePathEQ(v string) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldStoragePath, v))
}

// StoragePathNEQ applies the NEQ predicate on the "storage_path" field.
func StoragePathNEQ(v string) predicate.Blob {
	return predicate.Blob(sql.FieldNEQ(FieldStoragePath, v))
}

// StoragePathIn applies the In predicate on the "storage_path" field.
func StoragePathIn(vs ...string) predicate.Blob {
	return predicate.Blob(sql.FieldIn(FieldStoragePath, vs...))
}

// StoragePathNotIn applies the NotIn predicate on the "storage_path" field.
func StoragePathNotIn(vs ...string) predicate.Blob {
	return predicate.Blob(sql.FieldNotIn(FieldStoragePath, vs...))
}

// StoragePathGT applies the GT predicate on the "storage_path" field.
func StoragePathGT(v string) predicate.Blob {
	return predicate.Blob(sql.FieldGT(FieldStoragePath, v))
}

// StoragePathGTE applies the GTE predicate on the "storage_path" field.
func StoragePathGTE(v string) predicate.Blob {
	return predicate.Blob(sql.FieldGTE(FieldStoragePath, v))
}

// StoragePathLT applies the LT predicate on the "storage_path" field.
func StoragePathLT(v string) predicate.Blob {
	return predicate.Blob(sql.FieldLT(FieldStoragePath, v))
}

// StoragePathLTE applies the LTE predicate on the "storage_path" field.
func StoragePathLTE(v string) predicate.Blob {
	return predicate.Blob(sql.FieldLTE(FieldStoragePath, v))
}

// StoragePathContains applies the Contains predicate on the "storage_path" field.
func StoragePathContains(v string) predicate.Blob {
	return predicate.Blob(sql.FieldContains(FieldStoragePath, v))
}

// StoragePathHasPrefix applies the HasPrefix predicate on the "storage_path" field.
func StoragePathHasPrefix(v string) predicate.Blob {
	return predicate.Blob(sql.FieldHasPrefix(FieldStoragePath, v))
}

// StoragePathHasSuffix applies the HasSuffix predicate on the "storage_path" field.
func StoragePathHasSuffix(v string) predicate.Blob {
	return predicate.Blob(sql.FieldHasSuffix(FieldStoragePath, v))
}

// StoragePathEqualFold applies the EqualFold predicate on the "storage_path" field.
func StoragePathEqualFold(v string) predicate.Blob {
	return predicate.Blob(sql.FieldEqualFold(FieldStoragePath, v))
}

// StoragePathContainsFold applies the ContainsFold predicate on the "storage_path" field.
func StoragePathContainsFold(v string) predicate.Blob {
	return predicate.Blob(sql.FieldContainsFold(FieldStoragePath, v))
}

// UnreachableSinceEQ applies the EQ predicate on the "unreachable_since" field.
func UnreachableSinceEQ(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldUnreachableSince, v))
}

// UnreachableSinceNEQ applies the NEQ predicate on the "unreachable_since" field.
func UnreachableSinceNEQ(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldNEQ(FieldUnreachableSince, v))
}

// UnreachableSinceIn applies the In predicate on the "unreachable_since" field.
func UnreachableSinceIn(vs ...time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldIn(FieldUnreachableSince, vs...))
}

// UnreachableSinceNotIn applies the NotIn predicate on the "unreachable_since" field.
func UnreachableSinceNotIn(vs ...time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldNotIn(FieldUnreachableSince, vs...))
}

// UnreachableSinceGT applies the GT predicate on the "unreachable_since" field.
func UnreachableSinceGT(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldGT(FieldUnreachableSince, v))
}

// UnreachableSinceGTE applies the GTE predicate on the "unreachable_since" field.
func UnreachableSinceGTE(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldGTE(FieldUnreachableSince, v))
}

// UnreachableSinceLT applies the LT predicate on the "unreachable_since" field.
func UnreachableSinceLT(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldLT(FieldUnreachableSince, v))
}

// UnreachableSinceLTE applies the LTE predicate on the "unreachable_since" field.
func UnreachableSinceLTE(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldLTE(FieldUnreachableSince, v))
}

// UnreachableSinceIsNil applies the IsNil predicate on the "unreachable_since" field.
func UnreachableSinceIsNil() predicate.Blob {
	return predicate.Blob(sql.FieldIsNull(FieldUnreachableSince))
}

// UnreachableSinceNotNil applies the NotNil predicate on the "unreachable_since" field.
func UnreachableSinceNotNil() predicate.Blob {
	return predicate.Blob(sql.FieldNotNull(FieldUnreachableSince))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldLTE(FieldCreatedAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.Blob {
	return predicate.Blob(sql.FieldLTE(FieldLastSeenAt, v))
}

// HasFiles applies the HasEdge predicate on the "files" edge.
func HasFiles() predicate.Blob {
	return predicate.Blob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FilesTable, FilesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFilesWith applies the HasEdge predicate on the "files" edge with a given conditions (other predicates).
func HasFilesWith(preds ...predicate.File) predicate.Blob {
	return predicate.Blob(func(s *sql.Selector) {
		step := newFilesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Blob) predicate.Blob {
	return predicate.Blob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Blob) predicate.Blob {
	return predicate.Blob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Blob) predicate.Blob {
	return predicate.Blob(sql.NotPredicates(p))
}
