// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldAuthSource holds the string denoting the auth_source field in the database.
	FieldAuthSource = "auth_source"
	// FieldAuthRealm holds the string denoting the auth_realm field in the database.
	FieldAuthRealm = "auth_realm"
	// FieldExternalID holds the string denoting the external_id field in the database.
	FieldExternalID = "external_id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldCanManageAllShares holds the string denoting the can_manage_all_shares field in the database.
	FieldCanManageAllShares = "can_manage_all_shares"
	// FieldCanManageUsers holds the string denoting the can_manage_users field in the database.
	FieldCanManageUsers = "can_manage_users"
	// FieldDisabled holds the string denoting the disabled field in the database.
	FieldDisabled = "disabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeShares holds the string denoting the shares edge name in mutations.
	EdgeShares = "shares"
	// Table holds the table name of the user in the database.
	Table = "users"
	// SharesTable is the table that holds the shares relation/edge.
	SharesTable = "shares"
	// SharesInverseTable is the table name for the Share entity.
	// It exists in this package in order to avoid circular dependency with the "share" package.
	SharesInverseTable = "shares"
	// SharesColumn is the table column denoting the shares relation/edge.
	SharesColumn = "owner_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldAuthSource,
	FieldAuthRealm,
	FieldExternalID,
	FieldEmail,
	FieldDisplayName,
	FieldPasswordHash,
	FieldCanManageAllShares,
	FieldCanManageUsers,
	FieldDisabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// DefaultCanManageAllShares holds the default value on creation for the "can_manage_all_shares" field.
	DefaultCanManageAllShares bool
	// DefaultCanManageUsers holds the default value on creation for the "can_manage_users" field.
	DefaultCanManageUsers bool
	// DefaultDisabled holds the default value on creation for the "disabled" field.
	DefaultDisabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// AuthSource defines the type for the "auth_source" enum field.
type AuthSource string

// AuthSourceLocal is the default value of the AuthSource enum.
const DefaultAuthSource = AuthSourceLocal

// AuthSource values.
const (
	AuthSourceLocal AuthSource = "local"
	AuthSourceLdap  AuthSource = "ldap"
)

func (as AuthSource) String() string {
	return string(as)
}

// AuthSourceValidator is a validator for the "auth_source" field enum values. It is called by the builders before save.
func AuthSourceValidator(as AuthSource) error {
	switch as {
	case AuthSourceLocal, AuthSourceLdap:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for auth_source field: %q", as)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByAuthSource orders the results by the auth_source field.
func ByAuthSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthSource, opts...).ToFunc()
}

// ByAuthRealm orders the results by the auth_realm field.
func ByAuthRealm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthRealm, opts...).ToFunc()
}

// ByExternalID orders the results by the external_id field.
func ByExternalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByCanManageAllShares orders the results by the can_manage_all_shares field.
func ByCanManageAllShares(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanManageAllShares, opts...).ToFunc()
}

// ByCanManageUsers orders the results by the can_manage_users field.
func ByCanManageUsers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanManageUsers, opts...).ToFunc()
}

// ByDisabled orders the results by the disabled field.
func ByDisabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySharesCount orders the results by shares count.
func BySharesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSharesStep(), opts...)
	}
}

// ByShares orders the results by shares terms.
func ByShares(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSharesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSharesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SharesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SharesTable, SharesColumn),
	)
}
