// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Blob is the predicate function for blob builders.
type Blob func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// Share is the predicate function for share builders.
type Share func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
